[
"#!/bin/bash",
"",
"# Improving performance by running tasks concurrently",
"sleep 5 &",
"sleep 10 &",
"",
"# Handling multiple tasks simultaneously without blocking the main program",
"echo 'Main program running'",
"(sleep 3; echo 'Task 1 done') &",
"(sleep 6; echo 'Task 2 done') &",
"",
"# Updating UI elements in response to asynchronous events",
"echo 'Updating UI element'",
"(sleep 2; echo 'UI element updated') &",
"",
"# Processing large amounts of data in the background while the main thread remains responsive",
"echo 'Main thread processing'",
"(sleep 4; echo 'Data processing done') &",
"",
"# Performing network requests without freezing the application's user interface",
"echo 'Making network request'",
"(sleep 3; echo 'Network request complete') &",
"",
"wait"
]